#spring:
#   spring:
#   profiles: dev
#   datasource:
#     druid:
#        url: jdbc:mysql://192.168.124.17:3306/game_client?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useServerPrepStmts=false&allowMultiQueries=true
#        username: root
#        password: MyNewPass123!
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        type: com.alibaba.druid.pool.DruidDataSource
#        #initialSize: 10
#        minIdle: 50
#        maxActive: 100
#        maxWait: 60000
#        time-between-eviction-runs-millis: 60000
#mybatis-plus:
#    configuration:
#       log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
   profiles: dev
   datasource:
      gc:
         jdbcUrl: jdbc:mysql://127.0.0.1:3306/game_client?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useServerPrepStmts=false&allowMultiQueries=true
         username: root
         password: MyNewPass123!
         driver-class-name: com.mysql.cj.jdbc.Driver
         type: com.alibaba.druid.pool.DruidDataSource
         #initialSize: 10
         minIdle: 50
         maxActive: 100
         maxWait: 60000
         time-between-eviction-runs-millis: 60000
      gs:
         jdbcUrl: jdbc:mysql://127.0.0.1:3306/game_service?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useServerPrepStmts=false&allowMultiQueries=true
         username: root
         password: MyNewPass123!
         driver-class-name: com.mysql.cj.jdbc.Driver
         type: com.alibaba.druid.pool.DruidDataSource
         #initialSize: 10
         minIdle: 50
         maxActive: 100
         maxWait: 60000
         time-between-eviction-runs-millis: 60000
mybatis-plus:
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   mapper-locations: classpath*:/mapper/**/*.xml