spring:
   spring:
   profiles: dev
   datasource:
     druid:
        url: jdbc:mysql://127.0.0.1:3306/delivery?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
        username: root
        password: yang751659
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        #initialSize: 10
        minIdle: 50
        maxActive: 100
        maxWait: 60000
        time-between-eviction-runs-millis: 60000
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl